// ========== MOCK PATIENTS ==========
export const mockPatients = [
  {
    id: 'P-882019',
    regNo: 'PRN-2026-882019',
    phone: '9876543210',
    fullName: 'Priya Sharma',
    dob: '1985-10-14',
    gender: 'Female',
    maritalStatus: 'Married',
    govtId: 'AADHAAR-8921-4321-9901',
    occupation: 'Software Architect',
    guardianName: 'Ramesh Sharma',
    address: '12, Gandhi Nagar, Near Shiv Temple, Pune, Maharashtra 411001',
    emergencyContactName: 'Ramesh Sharma',
    emergencyContactPhone: '9876543211',
    bloodGroup: 'B+',
    allergies: ['Penicillin'],
    conditions: 'Hypertension',
    referringDoctor: 'Dr. Arjun Mehta',
    patientCategory: 'Corporate / Insurance',
    insuranceProvider: 'Star Health Comprehensive',
    policyNumber: 'STAR-POL-882019-X',
    registeredBy: 'Front Desk Admin',
    status: 'Active',
    relationshipToFamily: 'Self',
    photo: null,
    lastVisit: '2024-03-02',
  },
  {
    id: 'P-112233',
    regNo: 'PRN-2026-112233',
    phone: '9845001122',
    fullName: 'Rajesh Kumar',
    dob: '1980-12-05',
    gender: 'Male',
    maritalStatus: 'Married',
    govtId: 'PAN-ABCDE1234F',
    occupation: 'Senior Civil Engineer',
    guardianName: 'Late V. Kumar',
    address: '45, MG Road, Koramangala, Bengaluru, Karnataka 560034',
    emergencyContactName: 'Sunita Kumar',
    emergencyContactPhone: '9845001123',
    bloodGroup: 'O+',
    allergies: [],
    conditions: '',
    referringDoctor: '',
    patientCategory: 'VIP',
    insuranceProvider: 'HDFC Ergo Health Plan',
    policyNumber: 'HDFC-POL-112233-A',
    registeredBy: 'Front Desk Admin',
    status: 'Active',
    relationshipToFamily: 'Self',
    photo: null,
    lastVisit: '2024-01-15',
  },
  {
    id: 'P-112234',
    regNo: 'PRN-2026-112234',
    phone: '9845001122',
    fullName: 'Sunita Kumar',
    dob: '1982-04-22',
    gender: 'Female',
    maritalStatus: 'Married',
    govtId: 'AADHAAR-5544-2211-0099',
    occupation: 'High School Professor',
    guardianName: 'Rajesh Kumar',
    address: '45, MG Road, Koramangala, Bengaluru, Karnataka 560034',
    emergencyContactName: 'Rajesh Kumar',
    emergencyContactPhone: '9845001122',
    bloodGroup: 'A+',
    allergies: ['Sulfa'],
    conditions: 'Asthma',
    referringDoctor: '',
    patientCategory: 'VIP',
    insuranceProvider: 'HDFC Ergo Health Plan',
    policyNumber: 'HDFC-POL-112233-A',
    registeredBy: 'Front Desk Admin',
    status: 'Active',
    relationshipToFamily: 'Spouse',
    photo: null,
    lastVisit: '2024-02-20',
  },
  {
    id: 'P-112235',
    regNo: 'PRN-2026-112235',
    phone: '9845001122',
    fullName: 'Aryan Kumar',
    dob: '2010-09-14',
    gender: 'Male',
    maritalStatus: 'Single',
    govtId: 'ABHA-9900-1122-3344',
    occupation: 'Student (Grade 8)',
    guardianName: 'Rajesh Kumar',
    address: '45, MG Road, Koramangala, Bengaluru, Karnataka 560034',
    emergencyContactName: 'Rajesh Kumar',
    emergencyContactPhone: '9845001122',
    bloodGroup: 'O+',
    allergies: [],
    conditions: '',
    referringDoctor: '',
    patientCategory: 'General',
    insuranceProvider: 'HDFC Ergo Health Plan',
    policyNumber: 'HDFC-POL-112233-A',
    registeredBy: 'Front Desk Admin',
    status: 'Active',
    relationshipToFamily: 'Child',
    photo: null,
    lastVisit: '2023-11-05',
  },
  {
    id: 'P-776655',
    regNo: 'PRN-2026-776655',
    phone: '9900112233',
    fullName: 'Mohan Lal Gupta',
    dob: '1979-12-04',
    gender: 'Male',
    maritalStatus: 'Married',
    govtId: 'AADHAAR-7766-5544-3322',
    occupation: 'Business Owner',
    guardianName: 'Kavita Gupta',
    address: '22, Sector 15, Chandigarh, Punjab 160015',
    emergencyContactName: 'Kavita Gupta',
    emergencyContactPhone: '9900112234',
    bloodGroup: 'AB+',
    allergies: [],
    conditions: 'Diabetes Type 2',
    referringDoctor: 'Dr. Sanjay Patel',
    patientCategory: 'Senior Citizen',
    insuranceProvider: 'ICICI Lombard Health',
    policyNumber: 'ICICI-POL-776655-M',
    registeredBy: 'Front Desk Admin',
    status: 'Active',
    relationshipToFamily: 'Self',
    photo: null,
    lastVisit: '2024-04-10',
  },
];

// ========== MOCK DOCTORS ==========
export const mockDoctors = [
  {
    id: 'DOC-8832',
    name: 'Arjun Mehta',
    department: 'Cardiology',
    qualification: 'MD, FACC',
    contact: '+91 98765 43210',
    email: 'arjun.mehta@clinic.in',
    availableDays: ['Mon', 'Tue', 'Wed', 'Fri'],
    timeSlot: 'Full Day (09:00 - 17:00)',
    fee: 800,
    status: 'Active',
    photo: null,
  },
  {
    id: 'DOC-8845',
    name: 'Deepa Nair',
    department: 'Neurology',
    qualification: 'MD, DM',
    contact: '+91 98765 43211',
    email: 'deepa.nair@clinic.in',
    availableDays: ['Mon', 'Wed', 'Thu'],
    timeSlot: 'Morning OP (09:00 - 13:00)',
    fee: 1000,
    status: 'On Leave',
    photo: null,
  },
  {
    id: 'DOC-8901',
    name: 'Sanjay Patel',
    department: 'Pediatrics',
    qualification: 'MBBS, DCH',
    contact: '+91 97654 32100',
    email: 'sanjay.patel@clinic.in',
    availableDays: ['Tue', 'Thu', 'Sat'],
    timeSlot: 'Evening OP (14:00 - 18:00)',
    fee: 600,
    status: 'Active',
    photo: null,
  },
  {
    id: 'DOC-9012',
    name: 'Kavitha Reddy',
    department: 'General Medicine',
    qualification: 'MBBS, MD',
    contact: '+91 98765 43212',
    email: 'kavitha.reddy@clinic.in',
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    timeSlot: 'Full Day (09:00 - 17:00)',
    fee: 500,
    status: 'Active',
    photo: null,
  },
];

// ========== MOCK NURSES ==========
export const mockNurses = [
  {
    id: 'NUR-4011',
    name: 'Sunita Menon',
    department: 'ICU & Critical Care',
    qualification: 'B.Sc Nursing, RN',
    contact: '+91 98111 22334',
    email: 'sunita.menon@clinic.in',
    shift: 'Morning (06:00 - 14:00)',
    licenseNumber: 'RN-MH-44210',
    experience: '7',
    joiningDate: '2021-04-12',
    employmentType: 'Full-Time',
    specialties: ['ICU Monitoring', 'Ventilator Care', 'IV Cannulation'],
    assignedWard: 'Ward A - ICU Suite',
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    salary: '650000',
    bankDetails: 'ICICI Bank, Acc # 3344556677, IFSC ICIC000012',
    username: 's.menon',
    password: '••••••••',
    status: 'Active',
    photo: null,
  },
  {
    id: 'NUR-4012',
    name: 'Anjali Deshmukh',
    department: 'Emergency Ward',
    qualification: 'GNM, RN',
    contact: '+91 98222 33445',
    email: 'anjali.d@clinic.in',
    shift: 'Afternoon (14:00 - 22:00)',
    licenseNumber: 'RN-MH-55321',
    experience: '5',
    joiningDate: '2022-08-01',
    employmentType: 'Full-Time',
    specialties: ['Triage', 'Trauma Care', 'Wound Dressing'],
    assignedWard: 'Emergency Block - Ground',
    availableDays: ['Mon', 'Wed', 'Fri', 'Sat'],
    salary: '550000',
    bankDetails: 'HDFC Bank, Acc # 9988776655, IFSC HDFC000345',
    username: 'a.deshmukh',
    password: '••••••••',
    status: 'Active',
    photo: null,
  },
  {
    id: 'NUR-4013',
    name: 'Meenakshi Sundaram',
    department: 'Pediatric Ward',
    qualification: 'M.Sc Nursing (Pediatrics)',
    contact: '+91 98333 44556',
    email: 'm.sundaram@clinic.in',
    shift: 'Morning (06:00 - 14:00)',
    licenseNumber: 'RN-TN-77889',
    experience: '10',
    joiningDate: '2019-11-15',
    employmentType: 'Full-Time',
    specialties: ['Neonatal Care', 'Pediatric Vitals', 'Vaccination'],
    assignedWard: 'Ward B - Pediatrics',
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu'],
    salary: '780000',
    bankDetails: 'SBI Bank, Acc # 1122334455, IFSC SBIN000123',
    username: 'm.sundaram',
    password: '••••••••',
    status: 'On Leave',
    photo: null,
  },
  {
    id: 'NUR-4014',
    name: 'Rekha Sharma',
    department: 'Cardiology OPD',
    qualification: 'B.Sc Nursing',
    contact: '+91 98444 55667',
    email: 'rekha.sharma@clinic.in',
    shift: 'Full Day (08:00 - 20:00)',
    licenseNumber: 'RN-DL-11223',
    experience: '4',
    joiningDate: '2023-01-20',
    employmentType: 'Full-Time',
    specialties: ['ECG Triage', 'BP & Vitals Monitoring', 'OPD Triage'],
    assignedWard: 'OPD Ward A - Room 102',
    availableDays: ['Tue', 'Thu', 'Sat', 'Sun'],
    salary: '480000',
    bankDetails: 'Axis Bank, Acc # 6677889900, IFSC UTIB000567',
    username: 'r.sharma',
    password: '••••••••',
    status: 'Active',
    photo: null,
  }
];

// ========== MOCK APPOINTMENTS ==========
export const mockAppointments = [
  {
    id: 'APT-001',
    patientId: 'P-882019',
    patientName: 'Priya Sharma',
    doctorId: 'DOC-8832',
    doctorName: 'Dr. Arjun Mehta',
    department: 'Cardiology',
    date: '2024-05-15',
    timeSlot: '09:00 AM',
    reason: 'Routine follow-up for hypertension management.',
    token: 'TKN-042',
    status: 'Scheduled',
  },
  {
    id: 'APT-002',
    patientId: 'P-776655',
    patientName: 'Mohan Lal Gupta',
    doctorId: 'DOC-9012',
    doctorName: 'Dr. Kavitha Reddy',
    department: 'General Medicine',
    date: '2024-05-15',
    timeSlot: '10:00 AM',
    reason: 'Blood sugar follow-up.',
    token: 'TKN-043',
    status: 'Completed',
  },
];

// ========== MOCK NURSE QUEUE ==========
export const mockNurseQueue = [
  {
    token: 'A-012',
    patientId: 'P-882019',
    patientName: 'Priya Sharma',
    gender: 'F',
    age: 39,
    doctorName: 'Dr. Arjun Mehta',
    status: 'Pending',
    vitals: { bp: '130/85', pulse: '', temp: '98.6', weight: '', height: '', bmi: '', spo2: '', rbs: '' },
    chiefComplaint: '',
    nurseNotes: '',
    sentToDoctor: false,
  },
  {
    token: 'A-013',
    patientId: 'P-776655',
    patientName: 'Mohan Lal Gupta',
    gender: 'M',
    age: 44,
    doctorName: 'Dr. Kavitha Reddy',
    status: 'Pending',
    vitals: { bp: '', pulse: '', temp: '', weight: '', height: '', bmi: '', spo2: '', rbs: '' },
    chiefComplaint: '',
    nurseNotes: '',
    sentToDoctor: false,
  },
  {
    token: 'B-045',
    patientId: 'P-112233',
    patientName: 'Rajesh Kumar',
    gender: 'M',
    age: 43,
    doctorName: 'Dr. Arjun Mehta',
    status: 'Pending',
    vitals: { bp: '', pulse: '', temp: '', weight: '', height: '', bmi: '', spo2: '', rbs: '' },
    chiefComplaint: '',
    nurseNotes: '',
    sentToDoctor: false,
  },
  {
    token: 'A-011',
    patientId: 'P-112234',
    patientName: 'Sunita Kumar',
    gender: 'F',
    age: 41,
    doctorName: 'Dr. Kavitha Reddy',
    status: 'Done',
    vitals: { bp: '130/85', pulse: '78', temp: '98.2', weight: '62', height: '158', bmi: '24.8', spo2: '98', rbs: '105' },
    chiefComplaint: 'Cold and cough for 2 days',
    nurseNotes: 'Patient seems a bit anxious. BP slightly elevated.',
    sentToDoctor: true,
  },
];

// ========== MOCK CONSULTATION ==========
export const mockConsultationPatient = {
  name: 'Mohan Lal Gupta',
  age: '44M',
  id: 'P-776655',
  dob: '04/12/1979',
  token: 'A-013',
  vitals: {
    heartRate: { value: 98, unit: 'bpm', alert: true },
    bp: { value: '130/85', unit: 'mmHg', alert: false },
    temp: { value: '98.6', unit: '°F', alert: false },
    spo2: { value: '99%', alert: false },
  },
  history: {
    diagnoses: ['Diabetes Type 2'],
    allergies: [],
    conditions: 'Diabetes Type 2',
    prescriptions: ['Metformin 500mg - BD', 'Glimepiride 2mg - OD'],
  },
};

// ========== PAST CONSULTATIONS ==========
export const mockPastConsultations = [
  {
    id: 'CONS-991',
    patientId: 'P-112234', // Sunita Kumar
    date: '2023-11-15',
    doctorName: 'Dr. Arjun Mehta',
    department: 'Cardiology',
    diagnosis: 'Hypertension Stage 1',
    prescriptions: [
      { medicine: 'Amlodipine 5mg', dosage: '1 Tab', frequency: '1-0-0', duration: '30 Days' }
    ],
    labTests: ['Lipid Profile', 'ECG'],
    notes: 'Patient advised to reduce salt intake and walk daily.'
  },
  {
    id: 'CONS-992',
    patientId: 'P-112234', // Sunita Kumar
    date: '2024-02-20',
    doctorName: 'Dr. Sanjay Patel',
    department: 'Pediatrics',
    diagnosis: 'Viral Fever',
    prescriptions: [
      { medicine: 'Paracetamol 500mg', dosage: '1 Tab', frequency: 'SOS', duration: '3 Days' }
    ],
    labTests: ['Complete Blood Count (CBC)'],
    notes: 'Fever since 2 days, mild throat pain.'
  },
  {
    id: 'CONS-993',
    patientId: 'P-776655', // Mohan Lal Gupta
    date: '2024-01-10',
    doctorName: 'Dr. Deepa Nair',
    department: 'Neurology',
    diagnosis: 'Migraine',
    prescriptions: [
      { medicine: 'Naproxen 250mg', dosage: '1 Tab', frequency: 'SOS', duration: 'As needed' }
    ],
    labTests: [],
    notes: 'Frequent headaches on the left side.'
  },
  {
    id: 'CONS-994',
    patientId: 'P-882019', // Priya Sharma
    date: '2024-04-12',
    doctorName: 'Dr. Arjun Mehta',
    department: 'Cardiology',
    diagnosis: 'Essential Hypertension',
    prescriptions: [
      { medicine: 'Telmisartan 40mg', dosage: '1 Tab', frequency: '1-0-0', duration: '30 Days' },
      { medicine: 'Atorvastatin 10mg', dosage: '1 Tab', frequency: '0-0-1', duration: '30 Days' }
    ],
    labTests: ['Lipid Profile', 'HbA1c', 'ECG'],
    notes: 'BP recorded at 145/90. Advised DASH diet and regular blood pressure monitoring.'
  },
  {
    id: 'CONS-995',
    patientId: 'P-882019', // Priya Sharma
    date: '2024-06-05',
    doctorName: 'Dr. Kavitha Reddy',
    department: 'General Medicine',
    diagnosis: 'Acute Gastroenteritis',
    prescriptions: [
      { medicine: 'Ondansetron 4mg', dosage: '1 Tab', frequency: 'SOS', duration: '3 Days' },
      { medicine: 'Pantoprazole 40mg', dosage: '1 Cap', frequency: '1-0-0', duration: '5 Days' },
      { medicine: 'ORS Powder', dosage: '1 Sachet', frequency: 'In 1L water', duration: '3 Days' }
    ],
    labTests: ['Stool Routine', 'Electrolytes Panel'],
    notes: 'Severe cramping and dehydration. IV fluids administered in outpatient day-care.'
  },
  {
    id: 'CONS-996',
    patientId: 'P-112233', // Rajesh Kumar
    date: '2024-05-18',
    doctorName: 'Dr. Sanjay Patel',
    department: 'Orthopedics',
    diagnosis: 'Lumbar Spondylosis & Lower Back Strain',
    prescriptions: [
      { medicine: 'Diclofenac 75mg', dosage: '1 Tab', frequency: '1-0-1', duration: '5 Days' },
      { medicine: 'Thiocolchicoside 4mg', dosage: '1 Cap', frequency: '0-0-1', duration: '7 Days' }
    ],
    labTests: ['X-Ray Lumbosacral Spine', 'Vitamin D3'],
    notes: 'Patient reports sharp lower back pain after lifting heavy objects. Physiotherapy sessions recommended.'
  },
  {
    id: 'CONS-997',
    patientId: 'P-776655', // Mohan Lal Gupta
    date: '2024-06-22',
    doctorName: 'Dr. Kavitha Reddy',
    department: 'General Medicine',
    diagnosis: 'Type 2 Diabetes Mellitus - Follow Up',
    prescriptions: [
      { medicine: 'Metformin 500mg', dosage: '1 Tab', frequency: '1-0-1', duration: '60 Days' },
      { medicine: 'Glimepiride 2mg', dosage: '1 Tab', frequency: '1-0-0', duration: '60 Days' }
    ],
    labTests: ['Fasting Blood Sugar', 'Post Prandial Blood Sugar', 'HbA1c', 'Urine Routine'],
    notes: 'Fasting glucose improved to 118 mg/dL. Continue same medication regimen and 45-min daily brisk walk.'
  },
  {
    id: 'CONS-998',
    patientId: 'P-112234', // Sunita Kumar
    date: '2024-07-10',
    doctorName: 'Dr. Deepa Nair',
    department: 'Dermatology',
    diagnosis: 'Allergic Contact Dermatitis',
    prescriptions: [
      { medicine: 'Cetirizine 10mg', dosage: '1 Tab', frequency: '0-0-1', duration: '7 Days' },
      { medicine: 'Betamethasone Cream', dosage: 'Apply locally', frequency: 'BD', duration: '10 Days' }
    ],
    labTests: ['Serum IgE Level'],
    notes: 'Itching and rash on bilateral forearms following use of new synthetic detergent.'
  }
];

// ========== DEPARTMENTS ==========
export const departments = [
  'Cardiology', 'Neurology', 'Pediatrics', 'General Medicine',
  'Orthopedics', 'Dermatology', 'ENT', 'Ophthalmology',
  'Gynecology', 'Psychiatry', 'Radiology', 'Oncology',
  'Ayurveda', 'Dentistry', 'ICU & Critical Care', 'Emergency Ward'
];

// ========== DESIGNATIONS ==========
export const designations = [
  'Senior Consultant', 'Consultant', 'Resident Doctor', 'Head of Department',
  'Senior Staff Nurse (RN)', 'Staff Nurse', 'Head Nurse', 'Nursing Superintendent',
  'Hospital Administrator', 'Front Desk Executive', 'Billing Officer', 'Pharmacist',
  'Lab Technician', 'Ward Boy', 'Cleaning Staff'
];

// ========== LAB TESTS ==========
export const labTestsGroups = [
  {
    category: 'Hematology',
    tests: ['Complete Blood Count (CBC)', 'Hemoglobin (Hb)', 'ESR', 'Peripheral Smear', 'Blood Grouping']
  },
  {
    category: 'Biochemistry',
    tests: ['Lipid Profile', 'Blood Glucose (Fasting)', 'Blood Glucose (PP)', 'HbA1c', 'Liver Function Test (LFT)', 'Kidney Function Test (KFT)', 'Uric Acid', 'Serum Calcium']
  },
  {
    category: 'Pathology & Urine',
    tests: ['Urine Routine & Microscopy', 'Stool Routine', 'Urine Culture']
  },
  {
    category: 'Immunology & Serology',
    tests: ['Thyroid Profile (TSH)', 'Vitamin D', 'Vitamin B12', 'Iron Studies', 'Dengue NS1 Antigen', 'Malaria Antigen', 'Widal Test', 'CRP', 'Rheumatoid Factor (RA)']
  },
  {
    category: 'Cardiology & Imaging',
    tests: ['ECG', 'Chest X-Ray', 'Echocardiography', 'USG Abdomen']
  }
];

export const labTests = labTestsGroups.flatMap(g => g.tests);

// ========== DIAGNOSES ==========
export const diagnoses = [
  'Upper Respiratory Tract Infection (URTI)', 'Hypertension', 'Type 2 Diabetes Mellitus',
  'Migraine', 'Anxiety Disorder', 'Acute Gastroenteritis',
  'Urinary Tract Infection (UTI)', 'Pneumonia', 'Bronchial Asthma', 'GERD',
  'Iron Deficiency Anaemia', 'Hypothyroidism', 'Osteoarthritis',
  'Dengue Fever', 'Typhoid Fever', 'Viral Fever', 'Malaria',
  'Acute Pharyngitis', 'Sinusitis', 'Jaundice',
];

// ========== MEDICINES ==========
export const medicines = {
  Tablet: ['Paracetamol 500mg', 'Amoxicillin 500mg', 'Metformin 500mg', 'Amlodipine 5mg', 'Atorvastatin 10mg', 'Omeprazole 20mg', 'Aspirin 75mg', 'Azithromycin 500mg', 'Cetirizine 10mg', 'Pantoprazole 40mg'],
  Syrup: ['Paracetamol Syrup', 'Benadryl Cough Syrup', 'Calpol', 'Amoxicillin Dry Syrup', 'Cetirizine Syrup', 'Lactulose Syrup'],
  Injection: ['Insulin', 'Ceftriaxone 1g', 'Dexamethasone', 'Ondansetron 4mg', 'Diclofenac 75mg', 'Vitamin B12'],
  Capsule: ['Amoxicillin 500mg', 'Omeprazole 20mg', 'Vitamin D3 60K', 'Iron + Folic Acid', 'Doxycycline 100mg'],
  Drops: ['Otrivin Nasal Drops', 'Ciprofloxacin Eye Drops', 'Betadine', 'Ofloxacin Ear Drops'],
  Ointment: ['Soframycin', 'Mupirocin', 'Clotrimazole', 'Betamethasone'],
};

export const timeSlots = [
  '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM',
  '11:00 AM', '11:30 AM', '12:00 PM', '02:00 PM',
  '02:30 PM', '03:00 PM', '03:30 PM', '04:00 PM', '04:30 PM',
  '05:00 PM', '05:30 PM', '06:00 PM',
];

export const bloodGroups = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
export const daysOfWeek = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
export const doctorTimeSlots = [
  'Full Day (09:00 - 17:00)',
  'Morning OP (09:00 - 13:00)',
  'Evening OP (14:00 - 18:00)',
  'Night OP (18:00 - 21:00)',
];
export const qualifications = [
  'MBBS', 'MD', 'MS', 'DNB', 'DM', 'MCh',
  'MBBS, MD', 'MD, FACC', 'MD, DM', 'MBBS, DCH', 'MBBS, MS',
  'MBBS, DNB', 'MD, DNB', 'BDS', 'MDS', 'BAMS', 'MD (Ayurveda)',
];

export const indianStates = [
  'Andhra Pradesh', 'Assam', 'Bihar', 'Delhi', 'Goa', 'Gujarat',
  'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala',
  'Madhya Pradesh', 'Maharashtra', 'Odisha', 'Punjab', 'Rajasthan',
  'Tamil Nadu', 'Telangana', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
];

// ========== MOCK STAFFS ==========
export const mockStaffs = [
  {
    id: 'STF-001',
    fullName: 'Suresh Menon',
    role: 'Front Desk Supervisor',
    department: 'Reception & Admin',
    phone: '9845112233',
    email: 'suresh.m@aarogyaclinic.in',
    shift: 'Morning (08:00 AM - 04:00 PM)',
    status: 'Active',
    salary: '₹ 38,000 / mo',
    joinDate: '2021-04-15',
  },
  {
    id: 'STF-002',
    fullName: 'Kavita Nair',
    role: 'Senior Lab Technician',
    department: 'Pathology & Diagnostic Lab',
    phone: '9845112234',
    email: 'kavita.n@aarogyaclinic.in',
    shift: 'General (09:00 AM - 05:00 PM)',
    status: 'Active',
    salary: '₹ 42,000 / mo',
    joinDate: '2020-08-01',
  },
  {
    id: 'STF-003',
    fullName: 'Amitabh Verma',
    role: 'Chief Pharmacist & Billing',
    department: 'Pharmacy & Billing',
    phone: '9845112235',
    email: 'amitabh.v@aarogyaclinic.in',
    shift: 'General (09:00 AM - 05:00 PM)',
    status: 'Active',
    salary: '₹ 45,000 / mo',
    joinDate: '2019-11-10',
  },
  {
    id: 'STF-004',
    fullName: 'Ramesh Pawar',
    role: 'Ward Supervisor & Janitorial Lead',
    department: 'Sanitation & Facility',
    phone: '9845112236',
    email: 'ramesh.p@aarogyaclinic.in',
    shift: 'Evening (03:00 PM - 11:00 PM)',
    status: 'Active',
    salary: '₹ 28,000 / mo',
    joinDate: '2022-01-20',
  },
  {
    id: 'STF-005',
    fullName: 'Meenakshi Sundaram',
    role: 'Radiology / X-Ray Tech',
    department: 'Radiology & Imaging',
    phone: '9845112237',
    email: 'meenakshi.s@aarogyaclinic.in',
    shift: 'Morning (08:00 AM - 04:00 PM)',
    status: 'On Leave',
    salary: '₹ 40,000 / mo',
    joinDate: '2022-06-05',
  },
];

// ========== MOCK ROOMS & BEDS ==========
export const blocks = ['Block A (Main Wing)', 'Block B (Emergency)', 'Block C (Surgical)'];
export const floors = ['Ground Floor', '1st Floor', '2nd Floor', '3rd Floor'];

export const mockRooms = [
  {
    id: 'RM-101',
    block: 'Block A (Main Wing)',
    floor: '1st Floor',
    roomNo: '101',
    bedNo: 'A',
    type: 'General Bed',
    price: '₹ 1,500 / day',
    status: 'Occupied',
    patientId: 'P-882019',
    patientName: 'Priya Sharma',
    assignedDoctor: 'Dr. Arjun Mehta',
    assignedNurse: 'Sister Anjali Nair',
    admissionDate: '2026-07-22',
    notes: 'Vitals stable; daily ECG check required.',
  },
  {
    id: 'RM-102',
    block: 'Block A (Main Wing)',
    floor: '1st Floor',
    roomNo: '101',
    bedNo: 'B',
    type: 'General Bed',
    price: '₹ 1,500 / day',
    status: 'Available',
    patientId: null,
    patientName: null,
    assignedDoctor: null,
    assignedNurse: null,
    admissionDate: null,
    notes: 'Cleaned and sanitized for next admission.',
  },
  {
    id: 'RM-103',
    roomNo: 'Bed 103',
    ward: 'General Ward A (Male)',
    type: 'General Bed',
    price: '₹ 1,500 / day',
    status: 'Occupied',
    patientId: 'P-112233',
    patientName: 'Rajesh Kumar',
    assignedDoctor: 'Dr. Sanjay Patel',
    assignedNurse: 'Sister Divya Thomas',
    admissionDate: '2026-07-24',
    notes: 'Post-op observation; check blood sugar every 4 hrs.',
  },
  {
    id: 'RM-201',
    block: 'Block B (Emergency)',
    floor: 'Ground Floor',
    roomNo: 'ICU-1',
    bedNo: '01',
    type: 'ICU Ventilator Bed',
    price: '₹ 8,500 / day',
    status: 'Occupied',
    patientId: 'P-776655',
    patientName: 'Mohan Lal Gupta',
    assignedDoctor: 'Dr. Arjun Mehta',
    assignedNurse: 'Sister Anjali Nair',
    admissionDate: '2026-07-21',
    notes: 'Continuous cardiac telemetry & O2 saturation monitor.',
  },
  {
    id: 'RM-202',
    block: 'Block B (Emergency)',
    floor: 'Ground Floor',
    roomNo: 'ICU-1',
    bedNo: '02',
    type: 'ICU Ventilator Bed',
    price: '₹ 6,500 / day',
    status: 'Available',
    patientId: null,
    patientName: null,
    assignedDoctor: null,
    assignedNurse: null,
    admissionDate: null,
    notes: 'Ventilator standby checked.',
  },
  {
    id: 'RM-301',
    block: 'Block C (Surgical)',
    floor: '2nd Floor',
    roomNo: '301',
    bedNo: 'Single',
    type: 'Private AC Suite',
    price: '₹ 4,500 / day',
    status: 'Occupied',
    patientId: 'P-112234',
    patientName: 'Sunita Kumar',
    assignedDoctor: 'Dr. Neha Sharma',
    assignedNurse: 'Sister Divya Thomas',
    admissionDate: '2026-07-23',
    notes: 'Attendant couch provided; special diet ordered.',
  },
  {
    id: 'RM-302',
    block: 'Block C (Surgical)',
    floor: '2nd Floor',
    roomNo: '302',
    bedNo: 'Single',
    type: 'Private AC Suite',
    price: '₹ 4,500 / day',
    status: 'Cleaning / Maintenance',
    patientId: null,
    patientName: null,
    assignedDoctor: null,
    assignedNurse: null,
    admissionDate: null,
    notes: 'AC filter cleaning and linen replacement in progress.',
  },
];

// ========== MOCK PAYROLL & SALARY ==========
export const mockPayroll = [
  {
    id: 'PAY-101',
    empId: 'STF-501',
    name: 'Ananya Verma',
    role: 'Front Desk Receptionist',
    department: 'Reception & Patient Care',
    baseSalary: 35000,
    bonus: 2500,
    deductions: 500,
    netPayable: 37000,
    status: 'Paid',
    month: 'July 2026',
    payDate: '2026-07-01',
    bankAccount: 'HDFC •••• 4421',
  },
  {
    id: 'PAY-102',
    empId: 'STF-502',
    name: 'Ramesh Kulkarni',
    role: 'Senior Lab Technician',
    department: 'Pathology Lab',
    baseSalary: 45000,
    bonus: 3000,
    deductions: 0,
    netPayable: 48000,
    status: 'Paid',
    month: 'July 2026',
    payDate: '2026-07-01',
    bankAccount: 'ICICI •••• 8819',
  },
  {
    id: 'PAY-103',
    empId: 'STF-503',
    name: 'Vikram Joshi',
    role: 'Head Pharmacist',
    department: 'Pharmacy',
    baseSalary: 48000,
    bonus: 4000,
    deductions: 1000,
    netPayable: 51000,
    status: 'Pending',
    month: 'July 2026',
    payDate: 'Processing',
    bankAccount: 'SBI •••• 9901',
  },
  {
    id: 'PAY-104',
    empId: 'NUR-4011',
    name: 'Sunita Menon',
    role: 'ICU Head Nurse',
    department: 'ICU & Critical Care',
    baseSalary: 55000,
    bonus: 5000,
    deductions: 0,
    netPayable: 60000,
    status: 'Paid',
    month: 'July 2026',
    payDate: '2026-07-01',
    bankAccount: 'ICICI •••• 6677',
  },
  {
    id: 'PAY-105',
    empId: 'NUR-4012',
    name: 'Anjali Deshmukh',
    role: 'Emergency Nurse',
    department: 'Emergency Ward',
    baseSalary: 42000,
    bonus: 1500,
    deductions: 0,
    netPayable: 43500,
    status: 'Processing',
    month: 'July 2026',
    payDate: 'Processing',
    bankAccount: 'HDFC •••• 1122',
  },
  {
    id: 'PAY-106',
    empId: 'DOC-8821',
    name: 'Dr. Arjun Mehta',
    role: 'Senior Cardiologist',
    department: 'Cardiology',
    baseSalary: 180000,
    bonus: 25000,
    deductions: 5000,
    netPayable: 200000,
    status: 'Paid',
    month: 'July 2026',
    payDate: '2026-07-01',
    bankAccount: 'AXIS •••• 9012',
  },
];

// ========== MOCK SHIFTS & WORKING HOURS ==========
export const mockShifts = [
  {
    id: 'SHF-101',
    empId: 'STF-501',
    name: 'Ananya Verma',
    role: 'Front Desk Receptionist',
    department: 'Reception & Patient Care',
    assignedShift: 'Morning (08:00 AM - 04:00 PM)',
    shiftType: 'Morning',
    weeklyStandardHours: 40,
    loggedHours: 42.5,
    overtimeHours: 2.5,
    attendanceStatus: '⏰ On Duty (Checked In 07:55 AM)',
    lastCheckIn: 'Today, 07:55 AM',
  },
  {
    id: 'SHF-102',
    empId: 'STF-502',
    name: 'Ramesh Kulkarni',
    role: 'Senior Lab Technician',
    department: 'Pathology Lab',
    assignedShift: 'General (09:00 AM - 05:00 PM)',
    shiftType: 'General',
    weeklyStandardHours: 40,
    loggedHours: 40.0,
    overtimeHours: 0,
    attendanceStatus: '⏰ On Duty (Checked In 08:50 AM)',
    lastCheckIn: 'Today, 08:50 AM',
  },
  {
    id: 'SHF-103',
    empId: 'STF-503',
    name: 'Vikram Joshi',
    role: 'Head Pharmacist',
    department: 'Pharmacy',
    assignedShift: 'Evening (02:00 PM - 10:00 PM)',
    shiftType: 'Evening',
    weeklyStandardHours: 40,
    loggedHours: 38.0,
    overtimeHours: 0,
    attendanceStatus: '⏳ Scheduled (Starts at 02:00 PM)',
    lastCheckIn: 'Yesterday, 01:50 PM',
  },
  {
    id: 'SHF-104',
    empId: 'NUR-4011',
    name: 'Sunita Menon',
    role: 'ICU Head Nurse',
    department: 'ICU & Critical Care',
    assignedShift: 'Morning (06:00 AM - 02:00 PM)',
    shiftType: 'Morning',
    weeklyStandardHours: 48,
    loggedHours: 52.0,
    overtimeHours: 4.0,
    attendanceStatus: '⏰ On Duty (Checked In 05:45 AM)',
    lastCheckIn: 'Today, 05:45 AM',
  },
  {
    id: 'SHF-105',
    empId: 'NUR-4012',
    name: 'Anjali Deshmukh',
    role: 'Emergency Nurse',
    department: 'Emergency Ward',
    assignedShift: 'Night (10:00 PM - 06:00 AM)',
    shiftType: 'Night',
    weeklyStandardHours: 48,
    loggedHours: 48.0,
    overtimeHours: 0,
    attendanceStatus: '🌙 Shift Ended (Checked Out 06:05 AM)',
    lastCheckIn: 'Yesterday, 09:50 PM',
  },
  {
    id: 'SHF-106',
    empId: 'STF-505',
    name: 'Meenakshi Sundaram',
    role: 'X-Ray & CT Tech',
    department: 'Radiology & Imaging',
    assignedShift: 'Morning (08:00 AM - 04:00 PM)',
    shiftType: 'Morning',
    weeklyStandardHours: 40,
    loggedHours: 0,
    overtimeHours: 0,
    attendanceStatus: '🏖️ On Approved Leave',
    lastCheckIn: '2026-07-22, 04:00 PM',
  },
];

// ========== MOCK PHARMACY INVENTORY ==========
export const mockPharmacyInventory = [
  {
    id: 'MED-101',
    name: 'Tab. Amoxicillin + Clavulanic Acid 625mg (Augmentin)',
    category: 'Antibiotic',
    batchNo: 'BAT-2025-A88',
    expiryDate: '2027-11-30',
    stock: 240,
    minThreshold: 50,
    price: 185,
    supplier: 'GlaxoSmithKline (GSK) India',
    unit: 'Strip of 10',
    lastRestocked: '2026-07-10',
  },
  {
    id: 'MED-102',
    name: 'Tab. Paracetamol 650mg (Dolo 650)',
    category: 'Analgesic / Antipyretic',
    batchNo: 'BAT-2026-D12',
    expiryDate: '2028-04-15',
    stock: 25,
    minThreshold: 100,
    price: 32,
    supplier: 'Micro Labs Ltd',
    unit: 'Strip of 15',
    lastRestocked: '2026-06-20',
  },
  {
    id: 'MED-103',
    name: 'Syr. Ascoril LS Expectorant 100ml',
    category: 'Cough & Cold',
    batchNo: 'BAT-2025-L99',
    expiryDate: '2026-08-10',
    stock: 15,
    minThreshold: 30,
    price: 118,
    supplier: 'Glenmark Pharmaceuticals',
    unit: 'Bottle (100ml)',
    lastRestocked: '2026-05-15',
  },
  {
    id: 'MED-104',
    name: 'Tab. Pan-D (Pantoprazole 40mg + Domperidone 30mg)',
    category: 'Antacid / PPI',
    batchNo: 'BAT-2026-P04',
    expiryDate: '2028-01-20',
    stock: 310,
    minThreshold: 75,
    price: 140,
    supplier: 'Alkem Laboratories',
    unit: 'Strip of 15',
    lastRestocked: '2026-07-18',
  },
  {
    id: 'MED-105',
    name: 'Tab. Metformin 500mg SR (Glycomet)',
    category: 'Anti-Diabetic',
    batchNo: 'BAT-2025-M44',
    expiryDate: '2027-09-01',
    stock: 450,
    minThreshold: 100,
    price: 55,
    supplier: 'USV Private Limited',
    unit: 'Strip of 20',
    lastRestocked: '2026-07-01',
  },
  {
    id: 'MED-106',
    name: 'Tab. Telmisartan 40mg (Telma 40)',
    category: 'Anti-Hypertensive',
    batchNo: 'BAT-2026-T77',
    expiryDate: '2028-06-30',
    stock: 180,
    minThreshold: 60,
    price: 110,
    supplier: 'Glenmark Pharmaceuticals',
    unit: 'Strip of 15',
    lastRestocked: '2026-06-28',
  },
  {
    id: 'MED-107',
    name: 'Inj. Ceftriaxone 1g (Monocef)',
    category: 'Injectable Antibiotic',
    batchNo: 'BAT-2025-C11',
    expiryDate: '2026-08-05',
    stock: 12,
    minThreshold: 25,
    price: 65,
    supplier: 'Aristo Pharmaceuticals',
    unit: 'Vial (1g)',
    lastRestocked: '2026-04-10',
  },
  {
    id: 'MED-108',
    name: 'Cap. Rosuvastatin 10mg (Rosuvas 10)',
    category: 'Cardiac / Lipid',
    batchNo: 'BAT-2026-R22',
    expiryDate: '2028-03-12',
    stock: 220,
    minThreshold: 50,
    price: 195,
    supplier: 'Sun Pharma India',
    unit: 'Strip of 10',
    lastRestocked: '2026-07-12',
  },
];

// ========== MOCK PHARMACY E-PRESCRIPTION QUEUE ==========
export const mockPharmacyQueue = [
  {
    id: 'RX-9001',
    token: 'A-013',
    patientId: 'P-776655',
    patientName: 'Mohan Lal Gupta',
    age: '44M',
    doctorName: 'Dr. Kavitha Reddy',
    date: 'Today, 11:30 AM',
    status: 'Ready to Dispense',
    allergies: '⚠️ Penicillin, Sulfa Drugs (High Sensitivity)',
    diagnosis: 'Acute Upper Respiratory Infection & Mild Fever',
    items: [
      { medId: 'MED-101', name: 'Tab. Amoxicillin + Clavulanic Acid 625mg', dosage: '1-0-1 after meals', days: '5 days', qty: 10, price: 185 },
      { medId: 'MED-102', name: 'Tab. Paracetamol 650mg (Dolo 650)', dosage: '1-1-1 after food (SOS)', days: '3 days', qty: 15, price: 32 },
      { medId: 'MED-103', name: 'Syr. Ascoril LS Expectorant 100ml', dosage: '10ml thrice daily', days: '5 days', qty: 1, price: 118 }
    ],
    totalAmount: 335,
  },
  {
    id: 'RX-9002',
    token: 'C-012',
    patientId: 'P-998877',
    patientName: 'Anand Kumar',
    age: '52M',
    doctorName: 'Dr. Arjun Mehta',
    date: 'Today, 12:15 PM',
    status: 'Ready to Dispense',
    allergies: 'None Known',
    diagnosis: 'Hypertension & Type-2 Diabetes Mellitus Follow-up',
    items: [
      { medId: 'MED-106', name: 'Tab. Telmisartan 40mg (Telma 40)', dosage: '1-0-0 before breakfast', days: '30 days', qty: 30, price: 220 },
      { medId: 'MED-105', name: 'Tab. Metformin 500mg SR (Glycomet)', dosage: '1-0-1 after meals', days: '30 days', qty: 60, price: 165 },
      { medId: 'MED-108', name: 'Cap. Rosuvastatin 10mg (Rosuvas 10)', dosage: '0-0-1 at bedtime', days: '30 days', qty: 30, price: 585 }
    ],
    totalAmount: 970,
  },
  {
    id: 'RX-9003',
    token: 'A-011',
    patientId: 'P-112234',
    patientName: 'Sunita Kumar',
    age: '41F',
    doctorName: 'Dr. Kavitha Reddy',
    date: 'Yesterday, 04:45 PM',
    status: 'Dispensed',
    allergies: 'None Known',
    diagnosis: 'Cold, Cough & Mild Gastritis',
    items: [
      { medId: 'MED-104', name: 'Tab. Pan-D (Pantoprazole 40mg + Domperidone)', dosage: '1-0-0 empty stomach', days: '7 days', qty: 15, price: 140 },
      { medId: 'MED-102', name: 'Tab. Paracetamol 650mg (Dolo 650)', dosage: '1-0-1 SOS', days: '3 days', qty: 15, price: 32 }
    ],
    totalAmount: 172,
  },
];

// ========== MOCK PHARMACY BILLS / INVOICES ==========
export const mockPharmacyBills = [
  {
    id: 'INV-2026-088',
    rxId: 'RX-9003',
    patientName: 'Sunita Kumar',
    patientId: 'P-112234',
    date: '2026-07-24, 04:50 PM',
    itemsCount: 2,
    subtotal: 172,
    gst: 20.64,
    discount: 12.64,
    total: 180,
    paymentMethod: 'UPI / GPay (TXN-9988221)',
    status: 'Paid',
    items: [
      { name: 'Tab. Pan-D (Pantoprazole + Domperidone)', qty: 15, price: 140 },
      { name: 'Tab. Paracetamol 650mg (Dolo 650)', qty: 15, price: 32 }
    ],
  },
  {
    id: 'INV-2026-087',
    rxId: 'RX-8899',
    patientName: 'Vikramaditya Rao',
    patientId: 'P-445566',
    date: '2026-07-24, 02:15 PM',
    itemsCount: 3,
    subtotal: 540,
    gst: 64.8,
    discount: 24.8,
    total: 580,
    paymentMethod: 'Credit Card (HDFC POS)',
    status: 'Paid',
    items: [
      { name: 'Tab. Augmentin 625mg', qty: 20, price: 370 },
      { name: 'Syr. Ascoril LS', qty: 1, price: 118 },
      { name: 'Tab. Dolo 650mg', qty: 15, price: 52 }
    ],
  },
  {
    id: 'INV-2026-086',
    rxId: 'RX-8855',
    patientName: 'Meera Bai',
    patientId: 'P-332211',
    date: '2026-07-23, 11:20 AM',
    itemsCount: 1,
    subtotal: 220,
    gst: 26.4,
    discount: 6.4,
    total: 240,
    paymentMethod: 'Cash',
    status: 'Returned & Refunded',
    returnReason: 'Patient allergic reaction reported by Doctor; returned sealed strip.',
    items: [
      { name: 'Tab. Telmisartan 40mg (Telma 40)', qty: 30, price: 220 }
    ],
  },
];

